import type { PageManifestEntry } from "../content/page-types";

export const pageManifest = [
  {
    id: "home",
    path: "/",
    family: "home",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-04",
    primaryRoute: true,
    signature: "overlap",
    title: "Tri-Cities WA Photographer | It's A Keeper Photography",
    summary: "Warm, natural portraits across Richland, Kennewick and Pasco.",
  },
  {
    id: "family",
    path: "/family-photographer-tri-cities-wa/",
    contentPath: "family.json",
    family: "service",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-04",
    primaryRoute: true,
    signature: "overlap",
    title: "Family Photographer Tri-Cities WA | Golden-Hour Sessions",
    summary: "Relaxed, golden-hour family photography in the Tri-Cities.",
  },
  {
    id: "seniors",
    path: "/senior-photographer-tri-cities-wa/",
    contentPath: "seniors.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "arch",
    title: "Senior Pictures Tri-Cities WA | Class of 2027 Photographer",
    summary: "Confident, natural senior pictures photographed in golden light.",
  },
  {
    id: "newborn",
    path: "/newborn-photographer-tri-cities-wa/",
    contentPath: "newborn.json",
    family: "service",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-10",
    primaryRoute: true,
    signature: "crossing-line",
    title: "Newborn Photographer Tri-Cities WA | In-Home Sessions",
    summary:
      "Relaxed, baby-led newborn photography at home across Richland, Kennewick and Pasco, with room for the real rhythm of new family life.",
  },
  {
    id: "branding",
    path: "/branding-photographer-tri-cities-wa/",
    contentPath: "branding.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Branding Photographer in the Tri-Cities, WA | It's A Keeper",
    summary:
      "Custom business photography for Tri-Cities entrepreneurs, with warm brand images and commercial usage rights included.",
  },
  {
    id: "headshots",
    path: "/headshot-photographer-tri-cities-wa/",
    contentPath: "headshots.json",
    family: "service",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Service",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "Headshot Photographer Tri-Cities WA | I Come to You",
    summary:
      "Professional headshots in Richland, Kennewick and Pasco — photographed at your office with portable studio lighting.",
  },
  {
    id: "investment",
    path: "/investment/",
    contentPath: "investment.json",
    family: "trust",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "The Experience & Investment | It's A Keeper Photography",
    summary:
      "What it is like to work with Lisa, from planning and wardrobe guidance through the session, gallery viewing and printed photographs.",
  },
  {
    id: "about",
    path: "/about/",
    contentPath: "about.json",
    family: "trust",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "AboutPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-10",
    primaryRoute: true,
    signature: "arch",
    title: "Meet Lisa Weiss | Tri-Cities Photographer for 20 Years",
    summary:
      "Meet Lisa Weiss, the Richland photographer behind It's A Keeper Photography, with twenty years behind the camera and fourteen years in business.",
  },
  {
    id: "reviews",
    path: "/reviews/",
    contentPath: "reviews.json",
    family: "trust",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-12",
    primaryRoute: true,
    signature: "arch",
    title: "Client Reviews | It's A Keeper Photography",
    summary:
      "Read verified client stories from Tri-Cities families, seniors, couples and business clients photographed by Lisa Weiss.",
  },
  {
    id: "contact",
    path: "/contact/",
    contentPath: "contact.json",
    family: "trust",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "ContactPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-11",
    primaryRoute: true,
    signature: "overlap",
    title: "Session Pricing Estimate | It's A Keeper Photography",
    summary:
      "Build a personalized photography session pricing estimate, then plan the details with Lisa.",
  },
  {
    id: "richland",
    path: "/richland-wa-photographer/",
    contentPath: "richland.json",
    family: "city",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-09",
    primaryRoute: true,
    signature: "arch",
    title: "Richland WA Photographer | It's A Keeper Photography",
    summary: "Golden-hour portrait photography in Richland, Washington.",
  },
  {
    id: "kennewick",
    path: "/kennewick-wa-photographer/",
    contentPath: "kennewick.json",
    family: "city",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-09",
    primaryRoute: true,
    signature: "overlap",
    title: "Kennewick WA Photographer | It's A Keeper Photography",
    summary:
      "Warm, golden-toned portrait photography in Kennewick — seniors, families, newborns and branding. A richer, moodier alternative to light and airy, from Lisa.",
  },
  {
    id: "pasco",
    path: "/pasco-wa-photographer/",
    contentPath: "pasco.json",
    family: "city",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "WebPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-09",
    primaryRoute: true,
    signature: "overlap",
    title: "Pasco WA Photographer | It's A Keeper Photography",
    summary:
      "Pasco portrait photography by Lisa Weiss for seniors, families, in-home newborns, branding and professional headshots.",
  },
  {
    id: "journal",
    path: "/journal/",
    contentPath: "journal.json",
    family: "journal-hub",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "CollectionPage",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-11",
    primaryRoute: true,
    signature: "overlap",
    title: "Photography Journal | Tips & Locations From Lisa",
    summary: "First-hand portrait planning advice from a Tri-Cities photographer.",
  },
  {
    id: "locations-guide",
    path: "/journal/family-photo-locations-tri-cities/",
    contentPath: "journal-family-locations.json",
    family: "article",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-08",
    primaryRoute: true,
    signature: "overlap",
    title: "Where to Take Photos in the Tri-Cities: A Photographer's Guide",
    summary: "How Lisa chooses light, setting and season for portrait sessions across the Tri-Cities.",
  },
  {
    id: "senior-timing",
    path: "/journal/when-to-book-senior-pictures-tri-cities/",
    contentPath: "journal-senior-timing.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "crossing-line",
    title: "When to Take Senior Pictures: A Photographer's Timeline",
    summary:
      "A twenty-year senior photographer's season-by-season timeline for Tri-Cities senior pictures.",
  },
  {
    id: "newborn-comparison",
    path: "/journal/in-home-vs-studio-newborn-photography/",
    contentPath: "journal-newborn-comparison.json",
    family: "article",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    primaryRoute: true,
    signature: "overlap",
    title: "In-Home vs. Studio Newborn Photography: How to Choose",
    summary: "An honest comparison of in-home and studio newborn photography.",
  },
  {
    id: "branding-vs-headshots",
    path: "/journal/branding-photos-vs-headshots/",
    contentPath: "journal-branding-vs-headshots.json",
    family: "article",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "Article",
    sitemap: true,
    llms: true,
    lastModified: "2026-08-11",
    primaryRoute: true,
    signature: "crossing-line",
    title: "Branding Photos vs. Headshots: What's the Difference?",
    summary: "A plain-English comparison of branding photos and professional headshots.",
  },
  {
    id: "portfolio",
    path: "/portfolio/",
    family: "portfolio",
    contentStatus: "ready",
    searchVisibility: "index",
    schemaType: "CollectionPage",
    sitemap: true,
    llms: false,
    lastModified: "2026-07-21",
    primaryRoute: false,
    signature: "overlap",
    title: "Photography Portfolio | It's A Keeper Photography",
    summary: "A page-turning portrait portfolio from It's A Keeper Photography.",
  },
  {
    id: "privacy",
    path: "/privacy/",
    contentPath: "privacy.json",
    family: "utility",
    contentStatus: "draft",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: false,
    llms: false,
    primaryRoute: false,
    signature: "crossing-line",
    title: "Privacy | It's A Keeper Photography",
    summary: "Privacy information for It's A Keeper Photography.",
  },
  {
    id: "thank-you",
    path: "/thank-you/",
    contentPath: "thank-you.json",
    family: "utility",
    contentStatus: "ready",
    searchVisibility: "noindex",
    schemaType: "WebPage",
    sitemap: false,
    llms: false,
    primaryRoute: false,
    signature: "arch",
    title: "Thank You | It's A Keeper Photography",
    summary: "Your photography inquiry is with Lisa. She reads every message herself and replies personally.",
  },
] as const satisfies readonly PageManifestEntry[];

export const editorialManifest = pageManifest.filter(
  (entry): entry is (typeof pageManifest)[number] & { contentPath: string } =>
    "contentPath" in entry
);

export const topLevelEditorialManifest = editorialManifest.filter(
  (entry) => entry.path.split("/").filter(Boolean).length === 1
);

export const journalArticleManifest = editorialManifest.filter(
  (entry) => entry.family === "article"
);

export const getManifestEntry = (path: string) => {
  const normalized = path === "/" ? "/" : `/${path.replace(/^\/+|\/+$/g, "")}/`;
  return pageManifest.find((entry) => entry.path === normalized);
};
