// CONTENT PENDING [/]: [PENDIENTE: el bloque actual menciona los health challenges de la hija de Lisa y la sesión con ganador de Grammy — confirmar con Lisa antes de reutilizar cualquiera de los dos aquí o en /about/]
// CONTENT PENDING [/]: [La cifra 96 debe verificarse al momento de publicar.]
// CONTENT PENDING [/about/]: [NONBLOCKING: Antes de añadirlos, confirmar nombre/año del premio, permiso y detalle de la sesión Grammy, certificaciones/seguro/membresías, cualquier historia de salud y cifras/URL actualizadas de Google. La portada de Tri-Cities MOM ya está verificada y publicada.]
// CONTENT PENDING [/newborn-photographer-tri-cities-wa/]: [PENDIENTE NO BLOQUEANTE: confirmar si Lisa tiene formación de seguridad newborn (Q41) antes de publicar cualquier claim; la página no hace ese claim.]
// CONTENT PENDING [/privacy/]: [PENDIENTE: contenido legal de privacidad revisado y aprobado antes de publicar]
