query contentPageSite(
  $pagePath: String!
  $homepagePath: String!
  $settingsPath: String!
  $testimonialLimit: Float!
  $journalPageLimit: Float!
) {
  contentPage(relativePath: $pagePath) {
    ...ContentPageParts
  }
  homepage(relativePath: $homepagePath) {
    ...HomepageParts
  }
  settings(relativePath: $settingsPath) {
    ...SettingsParts
  }
  testimonialConnection(first: $testimonialLimit) {
    edges {
      node {
        ...TestimonialParts
      }
    }
  }
  journalPageConnection(first: $journalPageLimit, sort: "order") {
    edges {
      node {
        _sys {
          relativePath
        }
        ...JournalPageParts
      }
    }
  }
}
